source 'http://rubygems.org'
gem 'require_all'
gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'watir-webdriver-performance'
gem 'colorize'
gem 'pry'
gem 'pry-byebug'
gem 'pry-editline'
gem 'syntax'
gem 'slowhandcuke'
gem 'htmlcuke', '~> 2.0.4'